version: '{build}'

image: Visual Studio 2015
configuration: Release

platform:
  - x64

environment:
  JDK8_X64: C:\Program Files\Java\jdk1.8.0

  matrix:
    - JPY_PYTHON_HOME: C:\Python27-x64
      JPY_JDK_HOME: '%JDK8_X64%'


install:
  - call "C:\Program Files\Microsoft SDKs\Windows\v7.1\Bin\SetEnv.cmd" /%PLATFORM%
  - call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x86_amd64
  - set JDK_HOME=%JPY_JDK_HOME%
  # JAVA_HOME is used by Maven
  - set JAVA_HOME=%JPY_JDK_HOME%
  - set
  - call "%JPY_JDK_HOME%\bin\java.exe" -XshowSettings:properties -version
  - call "%JPY_PYTHON_HOME%\Scripts\pip.exe" install wheel
  - call "%JPY_PYTHON_HOME%\Scripts\pip.exe" install psutil

build_script:
  - set PATH=%JPY_PYTHON_HOME%;%JPY_PYTHON_HOME%\DLLs;%JPY_JDK_HOME%;%JPY_JDK_HOME%\bin;%PATH%
  - call "%JPY_PYTHON_HOME%\python.exe" setup.py --maven bdist_wheel
  - call git clone -q --branch=master https://github.com/illumon-public/illumon-jpy.git
  - dir /s

artifacts:
  - path: 'illumon-jpy\*.py'
    name: pys
